In [8]:
import pandas as pd
import os
from tqdm import tqdm

# Step 1. UKB

## Step 1.1 relative information

In [2]:
# parameters
info_fn = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/UKB/relative_information/relatives.info"

In [ ]:
info_colns = ["DOR", "relationship",
              "volid", "relid", 
              "volage", "relage", 
              "volsex", "relsex", 
              "Erx"]

In [8]:
# relative information format
df_pair = pd.read_csv(info_fn, sep='\t')

# convert to new column name
df_pair = df_pair.rename(columns={
    "eid": "volid", 
    "eid_rel": "relid",
    "age": "volage",
    "age_rel": "relage",
    "sex": "volsex",
    "sex_rel": "relsex",
    "rel_type": "relationship",
    "rx": "Erx",
    "Erx": "rx"
})

# recode sex
df_pair["volsex"] = df_pair["volsex"].replace({0: "F", 1: "M"})
df_pair["relsex"] = df_pair["relsex"].replace({0: "F", 1: "M"})

df_pair[info_colns].head()

   DOR relationship    volid    relid  volage  relage volsex relsex   Erx
0    1           DS  1000094  3653174      65      64      F      F  0.75
1    1          NaN  1000220  1691267      64      64      F      F   NaN
2    1          NaN  1000286  1571411      53      70      F      F   NaN
3    1          NaN  1000295  1045127      60      41      F      F   NaN
4    1          NaN  1000476  3599303      50      51      F      M   NaN

In [9]:
df_pair[info_colns].to_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/data/UKB/relative_information/relatives.formatted.info",
    sep='\t',
    index=False
)

## Step 1.2. phenotype

In [2]:
pheno_path = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/UKB/phenotype"

In [5]:
info_colns = ["eid", "pheno"]

In [3]:
pheno_fns = os.listdir(pheno_path)
len(pheno_fns)

111

In [7]:
for pheno_fn in pheno_fns:
    pheno = pheno_fn.split(".")[0]
    fn = f"{pheno_path}/{pheno_fn}"
    
    df_pheno = (pd.read_csv(fn, sep='\t')
                .rename(columns={"residual": "pheno"}))
    
    df_pheno[info_colns].to_csv(
        f"/data/jerrylee/pjt/BIGFAM.v.0.1/data/UKB/phenotype/{pheno}.phen",
        sep='\t',
        index=False
    )

# Step 2. GS

## Step 2.1 relative information

In [10]:
# parameters
info_fn = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/relative_information/relatives.info"

In [13]:
# relative information format
info_colns = ["DOR", "relationship",
              "volid", "relid", 
              "volage", "relage", 
              "volsex", "relsex", 
              "Erx"]
df_pair = pd.read_csv(info_fn, sep='\t')

# convert to new column name
df_pair = df_pair.rename(columns={
    "eid": "volid", 
    "eid_rel": "relid",
    "age": "volage",
    "age_rel": "relage",
    "sex": "volsex",
    "sex_rel": "relsex",
    "rel_type": "relationship",
})

# # recode sex
df_pair["volsex"] = df_pair["volsex"].replace({0: "F", 1: "M"})
df_pair["relsex"] = df_pair["relsex"].replace({0: "F", 1: "M"})

df_pair[info_colns].head()
# df_pair.head()

   DOR relationship  volid  relid  volage  relage volsex relsex       Erx
0    1           DS  18826  21244      50      36      F      F  0.750000
1    1        SS_DB  34422  23884      33      35      F      M  0.353553
2    1           DM  79198  67531      66      44      F      F  0.500000
3    1           DM  79198  67267      66      43      F      F  0.500000
4    1           DS  67531  67267      44      43      F      F  0.750000

In [16]:
df_pair[info_colns].to_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/relative_information/relatives.formatted.info",
    sep='\t',
    index=False
)

## Step 2.2 phenotype

In [10]:
pheno_path = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/phenotype"

In [11]:
info_colns = ["eid", "pheno"]

In [12]:
pheno_fns = os.listdir(pheno_path)
len(pheno_fns)

42

In [15]:
for pheno_fn in tqdm(pheno_fns):
    pheno = pheno_fn.split(".")[0]
    fn = f"{pheno_path}/{pheno_fn}"
    
    df_pheno = (pd.read_csv(fn, sep='\t')
                .rename(columns={"residual": "pheno"}))
    
    df_pheno[info_colns].to_csv(
        f"/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/phenotype/{pheno}.phen",
        sep='\t',
        index=False
    )

100%|██████████| 42/42 [00:03<00:00, 12.52it/s]