In [3]:
# GOAL :: Do familail relationship regression (FR-reg)

In [32]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
import sys; sys.path.append("/data/jerrylee/pjt/BIGFAM.v.0.1")
from BIGFAM import frreg
import importlib

# Step 1. Load data

In [33]:
# parameters
info_fn = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/relative_information/relatives.formatted.info"

In [34]:
# relative information format
df_pair = pd.read_csv(info_fn, sep='\t')
df_pair.head()

   DOR relationship  volid  relid  volage  relage volsex relsex       Erx
0    1           DS  18826  21244      50      36      F      F  0.750000
1    1        SS_DB  34422  23884      33      35      F      M  0.353553
2    1           DM  79198  67531      66      44      F      F  0.500000
3    1           DM  79198  67267      66      43      F      F  0.500000
4    1           DS  67531  67267      44      43      F      F  0.750000

# Step 2. FR-reg

In [82]:
pheno_path = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/phenotype"
frreg_path = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/frreg"

In [36]:
pheno_fns = os.listdir(pheno_path)
len(pheno_fns)

42

## Step 2.1 DOR level

In [99]:
warning_dicts = {}

for fn in tqdm(pheno_fns):
    pheno = fn.split(".")[0]
    pheno_fn = f"{pheno_path}/{fn}"
    df_pheno = pd.read_csv(pheno_fn, sep="\t")
    
    # merge pheno with relatives
    df_mrg = frreg.merge_pheno_info(df_pheno, df_pair)
    
    df_frreg, msgs = frreg.familial_relationship_regression_DOR(df_mrg)
    
    if len(msgs) > 0:
        warning_dicts[pheno] = msgs
        continue
    
    df_frreg.to_csv(
        f"{frreg_path}/DOR/{pheno}.DOR.frreg",
        sep='\t',
        index=False
    )

100%|██████████| 42/42 [00:17<00:00,  2.43it/s]

In [101]:
warning_dicts

{'QT_interval': ['Some FR-reg slope is NEGATIVE'],
 'PR_interval': ['Some FR-reg slope is NEGATIVE'],
 'LVMI_Rautaharju': ['Some FR-reg slope is NEGATIVE'],
 'absi': ['Some FR-reg slope is NEGATIVE'],
 'P_axis': ['Some FR-reg slope is NEGATIVE'],
 'QRS_duration': ['Some FR-reg slope is NEGATIVE'],
 'QRS_axis': ['Some FR-reg slope is NEGATIVE'],
 'T_axis': ['Some FR-reg slope is NEGATIVE'],
 'whr': ['Some FR-reg slope is NEGATIVE'],
 'QTC_interval': ['Some FR-reg slope is NEGATIVE'],
 'ECG_Count': ['Some FR-reg slope is NEGATIVE'],
 'P_duration': ['Some FR-reg slope is NEGATIVE'],
 'waist': ['Some FR-reg slope is NEGATIVE']}

In [102]:
df_frreg

   DOR     slope        se              p      n
0    1  0.270459  0.005220   0.000000e+00  34010
1    2  0.211559  0.008165  1.102113e-144  14328
2    3  0.176539  0.014040   1.034030e-35   4916

## Step 2.2 REL level

In [ ]:
warning_dicts = {}

for fn in tqdm(pheno_fns):
    pheno = fn.split(".")[0]
    pheno_fn = f"{pheno_path}/{fn}"
    df_pheno = pd.read_csv(pheno_fn, sep="\t")
    
    # merge pheno with relatives
    df_mrg = frreg.merge_pheno_info(df_pheno, df_pair)
    
    df_frreg, msgs = frreg.familial_relationship_regression_REL(df_mrg)
    
    if len(msgs) > 0:
        warning_dicts[pheno] = msgs
        continue
    
    df_frreg.to_csv(
        f"{frreg_path}/{pheno}.REL.frreg",
        sep='\t',
        index=False
    )

In [97]:
sorted(df_mrg["relationship"].unique())

['DF',
 'DF_DF',
 'DF_DF_DM',
 'DF_DF_SM',
 'DF_DM',
 'DF_SB',
 'DF_SB_DF',
 'DF_SB_SF',
 'DF_SF',
 'DF_SF_DF',
 'DF_SF_SF',
 'DF_SM',
 'DF_SM_DM',
 'DF_SM_SM',
 'DF_SS_DB',
 'DF_SS_DB_DM',
 'DF_SS_DB_SM',
 'DM',
 'DM_DF',
 'DM_DF_DF',
 'DM_DM',
 'DM_DM_DM',
 'DM_DM_SM',
 'DM_DS',
 'DM_DS_DM',
 'DM_DS_SM',
 'DM_SM',
 'DM_SM_DF',
 'DM_SM_SF',
 'DM_SS_DB',
 'DM_SS_DB_DF',
 'DM_SS_DB_SF',
 'DS',
 'DS_DM',
 'DS_SM',
 'SB',
 'SB_DF',
 'SB_SF',
 'SF',
 'SF_DF',
 'SF_SB',
 'SF_SB_DF',
 'SF_SB_SF',
 'SF_SF',
 'SF_SF_DF',
 'SF_SF_SF',
 'SF_SF_SM',
 'SF_SM',
 'SF_SM_DM',
 'SF_SM_SM',
 'SF_SS_DB',
 'SF_SS_DB_DM',
 'SF_SS_DB_SM',
 'SM',
 'SM_DF',
 'SM_DF_DF',
 'SM_DM',
 'SM_DM_DM',
 'SM_DM_SM',
 'SM_DS',
 'SM_DS_DM',
 'SM_DS_SM',
 'SM_SF',
 'SM_SM',
 'SM_SM_DF',
 'SM_SM_SF',
 'SM_SS_DB',
 'SM_SS_DB_DF',
 'SM_SS_DB_SF',
 'SS_DB',
 'SS_DB_DF',
 'SS_DB_DM',
 'SS_DB_SF',
 'SS_DB_SM']

In [98]:
importlib.reload(frreg)

In [ ]:
# output : 
# [DOR, sex_type, rel_type, slope, rx, n]
# [DOR, slope, rx, n]