In [3]:
# GOAL :: Do familail relationship regression (FR-reg)

In [14]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
import sys; sys.path.append("/data/jerrylee/pjt/BIGFAM.v.0.1")
from BIGFAM import frreg
import importlib

# Step 1. Load data

In [15]:
# parameters
info_fn = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/relative_information/relatives.formatted.info"

In [16]:
# relative information format
df_pair = pd.read_csv(info_fn, sep='\t')
df_pair.head()

   DOR relationship  volid  relid  volage  relage volsex relsex       Erx
0    1           DS  18826  21244      50      36      F      F  0.750000
1    1        SS_DB  34422  23884      33      35      F      M  0.353553
2    1           DM  79198  67531      66      44      F      F  0.500000
3    1           DM  79198  67267      66      43      F      F  0.500000
4    1           DS  67531  67267      44      43      F      F  0.750000

# Step 2. FR-reg

In [11]:
pheno_path = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/phenotype"
frreg_path = "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GS/frreg"

In [12]:
pheno_fns = os.listdir(pheno_path)
len(pheno_fns)

40

## Step 2.1 DOR level

In [130]:
warning_dicts = {}

for fn in tqdm(pheno_fns):
    pheno = fn.split(".")[0]
    pheno_fn = f"{pheno_path}/{fn}"
    df_pheno = pd.read_csv(pheno_fn, sep="\t")
    
    # merge pheno with relatives
    df_mrg = frreg.merge_pheno_info(df_pheno, df_pair)
    
    df_frreg, msgs = frreg.familial_relationship_regression_DOR(df_mrg)
    
    if len(msgs) > 0:
        warning_dicts[pheno] = msgs
        continue
    
    df_frreg.to_csv(
        f"{frreg_path}/DOR/{pheno}.DOR.frreg",
        sep='\t',
        index=False
    )

100%|██████████| 111/111 [02:13<00:00,  1.20s/it]

In [131]:
warning_dicts

{'Glucose': ['Some FR-reg slope is NEGATIVE'],
 'Nucleated_red_blood_cell_percentage': ['Some FR-reg slope is NEGATIVE'],
 'Nucleated_red_blood_cell_count': ['Some FR-reg slope is NEGATIVE']}

In [113]:
df_frreg

   DOR     slope        se              p      n
0    1  0.270459  0.005220   0.000000e+00  34010
1    2  0.211559  0.008165  1.102113e-144  14328
2    3  0.176539  0.014040   1.034030e-35   4916

## Step 2.2 REL level

In [13]:
warning_dicts = {}

for fn in tqdm(pheno_fns):
    pheno = fn.split(".")[0]
    pheno_fn = f"{pheno_path}/{fn}"
    df_pheno = pd.read_csv(pheno_fn, sep="\t")
    
    # merge pheno with relatives
    df_mrg = frreg.merge_pheno_info(df_pheno, df_pair)
    
    df_frreg, msgs = frreg.familial_relationship_regression_REL(df_mrg)
    
    # if len(msgs) > 0:
    #     warning_dicts[pheno] = msgs
    #     continue
    
    # save results
    df_frreg.to_csv(
        f"{frreg_path}/REL/{pheno}.REL.frreg",
        sep='\t',
        index=False
    )

100%|██████████| 40/40 [00:54<00:00,  1.37s/it]