In [1]:
import numpy as np
import pandas as pd
import os
import statsmodels.formula.api as smf
from tqdm import tqdm

import seaborn as sns
import matplotlib.pyplot as plt; plt.style.use("dark_background")

In [3]:
df = pd.read_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/tables/ST5.tsv",
    sep='\t'
)
df.sample(4)

,pheno,sex,BIGFAM,lower_BIGFAM (2.5%),upper_BIGFAM (97.5%),GCTA,GCTA (2.5%),GCTA (97.5%)
20,Leg_fat-free_mass__left_,male,0.011556,0.000016,0.029174,0.013420,0.008632,0.018208
2,"Forced_expiratory_volume_in_1-second__FEV1_,_B...",all,0.014203,0.002899,0.026878,0.005298,0.002512,0.008084
21,Leg_fat-free_mass__right_,male,0.018509,0.001596,0.034741,0.013445,0.008647,0.018242
1,Cholesterol,all,0.004557,0.000883,0.007840,0.002696,0.000513,0.004878

In [13]:
tmp = df[df["sex"] == "male"]

corrs = []
for p in tmp["pheno"].unique():
    ttmp = tmp[tmp["pheno"] != p].copy()
    corrs += [ttmp[["BIGFAM", "GCTA"]].corr().iloc[0, 1]]

len(tmp["pheno"].unique()), np.median(corrs), np.percentile(corrs, 2.5), np.percentile(corrs, 97.5)

(16, 0.9493913773116859, 0.9371197076970167, 0.969575877278895)

In [14]:
tmp = df[df["sex"] == "female"]

corrs = []
for p in tmp["pheno"].unique():
    ttmp = tmp[tmp["pheno"] != p].copy()
    corrs += [ttmp[["BIGFAM", "GCTA"]].corr().iloc[0, 1]]

len(tmp["pheno"].unique()), np.median(corrs), np.percentile(corrs, 2.5), np.percentile(corrs, 97.5)

(16, 0.6504317477819959, 0.5390597143408344, 0.7184669958883227)

In [58]:
ref = pd.read_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/figures/data/obj1.v3.tsv",
    sep='\t'
)
ref_ps = ref[ref["cohort"] == "UKB"]["pheno"]
len(ref_ps)

109

In [59]:
df = pd.read_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/data/X/X.UKB.tsv",
    sep='\t'
)
# df = df[df["weight"] == 2].reset_index(drop=True)

In [62]:
df_bigfam = df[df["weight"] == 2]
print(df_bigfam.shape)

df_bigfam[df_bigfam["pheno"].isin(ref_ps) & (df_bigfam["lower_Vx"] > 1e-6)].shape

(95, 6)

(14, 6)

In [65]:
df = pd.read_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/data/UKB/relative_information/relatives.formatted.info",
    sep='\t'
)
df = df.dropna()

In [66]:
uniq_ids = set(df["volid"]) | set(df["relid"])
len(uniq_ids)

48912

In [67]:
df

,DOR,rcode,relationship,volid,relid,volage,relage,volsex,relsex,Erx
0,1,SB,daughter-sister,1000094,3653174,65,64,F,F,0.750000
10,1,PC,son-mother,1000907,1389692,49,69,M,F,0.707107
11,1,SB,daughter-sister,1001023,2992012,49,53,F,F,0.750000
12,1,SB,different-sex-sibling,1001023,3808910,49,47,F,M,0.353553
14,1,PC,daughter-mother,1001135,4948669,44,67,F,F,0.500000
...,...,...,...,...,...,...,...,...,...,...
81312,3,1C,son-mother-brother-daughter,6021456,2136508,46,51,F,M,0.176777
81316,3,1C,son-(father-brother)/(father-sister)-daughter,6022327,1587095,60,59,M,F,0.000000
81317,3,1C,son-(father-sister)/(father-sister)/(mother-br...,6022398,2440614,65,62,M,M,0.000000
81321,3,1C,son-(father-brother)/(father-sister)-daughter,6023723,4863061,62,64,F,M,0.000000
81324,3,1C,son-(father-sister)/(father-sister)/(mother-br...,6024486,3148753,58,56,M,M,0.000000

In [42]:
tmp = df[(df["weight"] == 2) & (df["lower_Vx_BIGFAM"] > 1e-6)]
len(tmp["pheno"].unique())

13

In [43]:
tmp

,pheno,weight,lambda,Vx_BIGFAM,lower_Vx_BIGFAM,upper_Vx_BIGFAM,Vx_GCTA,lower_Vx_GCTA,upper_Vx_GCTA
8,Waist_circumference,2,0.482339,0.012129,0.004281,0.021894,0.004954,0.002788,0.007120
17,LDL_direct,2,0.300305,0.003493,0.000222,0.008383,0.002388,0.000205,0.004571
23,Cholesterol,2,0.305977,0.004557,0.000883,0.007840,0.002696,0.000513,0.004878
36,Leg_fat_mass__right_,2,0.507110,0.010852,0.002898,0.020673,0.004274,0.002100,0.006447
54,Trunk_fat_mass,2,0.534141,0.012884,0.003051,0.024388,0.006048,0.003820,0.008276
66,Leg_fat-free_mass__left_,2,0.624153,0.015959,0.002643,0.028220,0.007571,0.005312,0.009829
77,Leg_fat-free_mass__right_,2,0.636641,0.017931,0.004927,0.032582,0.007790,0.005515,0.010064
89,Leg_fat_mass__left_,2,0.498261,0.012118,0.003760,0.022962,0.004555,0.002362,0.006747
100,C-reactive_protein,2,0.255694,0.004848,0.001970,0.008798,0.002313,0.000151,0.004475
109,Monocyte_count,2,0.437731,0.007973,0.000016,0.016083,0.002645,0.000494,0.004796
117,Immature_reticulocyte_fraction,2,0.381195,0.006670,0.001728,0.012753,0.003586,0.001388,0.005785
129,"Forced_expiratory_volume_in_1-second__FEV1_,_B...",2,0.498362,0.014203,0.002899,0.026878,0.005298,0.002512,0.008084
140,Whole_body_fat_mass,2,0.522758,0.010372,0.000710,0.019092,0.005386,0.003166,0.007606

In [26]:
tt = pd.read_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/data/GCTA/X.all.gcta",
    sep='\t'
)

In [29]:
ttt = tt[tt["sex"] == "all"]
ttt[(ttt["X_GCTA"] - 1.96 * ttt["se_X_GCTA"]) > 1e-6]

                                       pheno  n_meta  sex    X_GCTA  se_X_GCTA
3      Hair_colour__natural,_before_greying_      30  all  0.004818   0.001090
6                                      Urate      30  all  0.003119   0.001110
9                            Standing_height      30  all  0.020603   0.001332
12                                     IGF-1      30  all  0.007575   0.001204
15                            Monocyte_count      30  all  0.002645   0.001097
..                                       ...     ...  ...       ...        ...
369  Index_of_Multiple_Deprivation__England_      30  all  0.005455   0.001268
375                     Past_tobacco_smoking      30  all  0.003393   0.001137
378                Arm_fat-free_mass__right_      30  all  0.008903   0.001177
381              Forced_vital_capacity__FVC_      30  all  0.006721   0.001240
387                 Alanine_aminotransferase      30  all  0.002509   0.001097

[115 rows x 5 columns]

In [55]:
ref = pd.read_csv(
    "/data/jerrylee/pjt/BIGFAM.v.0.1/figures/data/obj1.v3.tsv",
    sep='\t'
)
ref_ps = ref[ref["cohort"] == "UKB"]["pheno"]

In [35]:
ppp = ttt[ttt["pheno"].isin(ref[ref["cohort"] == "UKB"]["pheno"])]
ppp[(ppp["X_GCTA"] - 1.96 * ppp["se_X_GCTA"]) > 1e-6]

,pheno,n_meta,sex,X_GCTA,se_X_GCTA
3,"Hair_colour__natural,_before_greying_",30,all,0.004818,0.001090
6,Urate,30,all,0.003119,0.001110
9,Standing_height,30,all,0.020603,0.001332
12,IGF-1,30,all,0.007575,0.001204
15,Monocyte_count,30,all,0.002645,0.001097
...,...,...,...,...,...
363,"Heel_bone_mineral_density__BMD__T-score,_autom...",30,all,0.005038,0.001818
375,Past_tobacco_smoking,30,all,0.003393,0.001137
378,Arm_fat-free_mass__right_,30,all,0.008903,0.001177
381,Forced_vital_capacity__FVC_,30,all,0.006721,0.001240
387,Alanine_aminotransferase,30,all,0.002509,0.001097