In [1]:
import pandas as pd
from BIGFAM import frreg

# Step 1. Load family data

In [2]:
df_pair = pd.read_csv("test.info", sep='\t')
df_pheno = pd.read_csv("test.phen", sep='\t')

In [3]:
df_pair.head()

,DOR,rcode,relationship,volid,relid,volage,relage,volsex,relsex,Erx
0,1,SB,daughter-sister,2659612,4083248,54,52,F,F,0.75
1,1,SB,daughter-sister,4335083,1979162,51,52,F,F,0.75
2,1,SB,daughter-sister,2726892,5383149,62,61,F,F,0.75
3,1,SB,daughter-sister,4559683,5228233,55,58,F,F,0.75
4,1,SB,daughter-sister,1268792,5443453,59,55,F,F,0.75

In [4]:
df_pheno.head()

       eid     pheno
0  1007230 -0.660626
1  1018151 -0.947998
2  1018195  0.798099
3  1042880  0.280435
4  1101858  0.921073

In [5]:
# merge info & phenotype
df_mrg = frreg.merge_pheno_info(df_pheno, df_pair)
df_mrg.head()

,DOR,rcode,relationship,volid,relid,volage,relage,volsex,relsex,Erx,volpheno,relpheno
0,1,SB,daughter-sister,2659612,4083248,54,52,F,F,0.75,1.407273,0.733638
1,1,SB,daughter-sister,4335083,1979162,51,52,F,F,0.75,0.391380,-0.679524
2,1,SB,daughter-sister,2726892,5383149,62,61,F,F,0.75,0.504905,-0.615189
3,1,SB,daughter-sister,4559683,5228233,55,58,F,F,0.75,-0.923403,-0.064528
4,1,SB,daughter-sister,1268792,5443453,59,55,F,F,0.75,-0.118443,-0.216822

# Step 2. Degree-Of-Relatedness level

In [9]:
df_frreg_DOR, _ = frreg.familial_relationship_regression_DOR(
    df_mrg,
    thred_pair=2, # hard-cut the small number of DOR pairs
    std_pheno=True,
    remove_outlier=True
)

In [10]:
df_frreg_DOR

   DOR     slope        se         p   n
0    1  0.301036  0.114802  0.010741  70
1    2  0.187790  0.101512  0.068735  68
2    3  0.376803  0.104216  0.000526  80

# Step 3. Relationship level

In [11]:
df_frreg_REL, _ = frreg.familial_relationship_regression_REL(
    df_mrg,
    thred_pair=2, # hard-cut the small number of DOR pairs
    std_pheno=True,
    remove_outlier=True
)

In [12]:
df_frreg_REL

,DOR,relationship,sex_type,Erx,slope,se,p,n
0,1,daughter-father,FM,0.707107,-2.302742,1.568348,0.176095,10
1,1,daughter-mother,FF,0.500000,-0.568361,0.303745,0.094122,10
2,1,daughter-sister,FF,0.750000,0.347675,0.446153,0.455820,10
3,1,different-sex-sibling,FM,0.353553,0.395370,0.087519,0.001452,10
4,1,son-brother,MM,0.500000,0.621312,0.196715,0.011579,10
5,1,son-father,MM,0.000000,0.464057,0.225041,0.069244,10
6,1,son-mother,FM,0.707107,0.004633,0.372473,0.990346,10
7,2,daughter-father-brother,FM,0.353553,0.208420,0.291029,0.492063,10
8,2,daughter-father-sister,FF,0.250000,0.025448,0.356361,0.944632,10
9,2,daughter-mother-brother,FM,0.176777,0.231787,0.370437,0.551351,8
10,2,daughter-mother-sister,FF,0.375000,0.039710,0.317984,0.903363,10
11,2,son-father-brother,MM,0.000000,0.324399,0.158353,0.070776,10
12,2,son-mother-brother,MM,0.250000,0.128785,0.484875,0.796528,10
13,2,son-mother-sister,FM,0.530330,0.224314,0.409212,0.596914,10
14,3,daughter-(father/mother)-brother-daughter,FF,0.250000,-0.084830,0.062126,0.205262,10
15,3,daughter-father-sister-daughter,FF,0.125000,1.493513,0.240406,0.000157,10
16,3,daughter-mother-sister-daughter,FF,0.187500,1.008353,0.161560,0.000151,10
17,3,son-(father-brother)/(father-sister)-daughter,FM,0.000000,0.712102,0.391012,0.101913,10
18,3,son-(father-sister)/(father-sister)/(mother-br...,MM,0.000000,0.132623,0.311467,0.680254,10
19,3,son-mother-brother-daughter,FM,0.176777,0.258336,0.505895,0.621885,10
20,3,son-mother-sister-daughter,FM,0.265165,0.052710,0.186641,0.784013,10
21,3,son-mother-sister-son,MM,0.375000,-0.675330,0.237892,0.019441,10